---
- name: RenixPi Configuration
  hosts: localhost
  roles:
    - common
  tasks:
    - name: "Add grafana apt key"
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: yes
    - name: "Add grafana repo"
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
      become: yes
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - grafana
      become: yes
    - name: start monitoring services
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: "grafana-server"
      become: yes
    - name: clone analytics and opendsh
      git:
        repo: 'git@github.com:{{ item }}.git'
        dest: '~/{{ item }}'
        update: no
      loop:
        - "RenixPi/RenixAnalytics"
        - "OpenDsh/dash"
        - "RenixPi/RenixRadio"
    - name: disable screensaver, energysaver and mouse pointer
      lineinfile:
        path: "/etc/xdg/lxsession/LXDE-pi/autostart"
        line: "{{ item }}"
      loop:
        - '@xrandr --output HDMI-1 --mode 1280x720'
    - name: boot changes
      lineinfile:
        path: "/boot/config.txt"
        line: "{{ item }}"
      loop:
        - 'disable_overscan=1'

#    - name: install RenixAnalytics dependencies
#      npm:
#        path: /home/pi/RenixAnalytics
#    - name: run opendash install
#      ansible.builtin.shell:
#        cmd: "install.sh"
#        chdir: "~/dash"

# add to bashrc
# export XDG_RUNTIME_DIR=/run/user/$(id -u pi)
# sudo loginctl enable-linger pi
# systemctl --user daemon-reload
# systemctl --user enable renixradio
# systemctl --user start renixradio

# install renixradio dependencies
# sudo apt-get install libatlas-base-dev
# install

# screen resolution
# cvt 1024 600 60
# xrandr --newmode <line from above>
# xrandr --addmode HDMI-n <mode from above>
# xrandr -s 1680x1050
# xrandr --output VGA1 --mode "1920x1080_60.00"
