---
- name: RenixPi Configuration
  hosts: localhost
  roles:
    - common
  tasks:
    - name: "Add grafana apt key"
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: yes
    - name: "Add grafana repo"
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
      become: yes
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - grafana
    - name: start monitoring services
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: "grafana-server"
    - name: clone analytics and opendsh
      git:
        repo: 'git@github.com:{{ item }}.git'
        dest: '~/{{ item }}'
        update: no
      loop:
        - "RenixPi/RenixAnalytics"
        - "OpenDsh/dash"
      become: yes
    - name: install RenixAnalytics dependencies
      npm:
        path: /home/pi/RenixAnalytics
    - name: run opendash install
      ansible.builtin.shell:
        cmd: "install.sh"
        chdir: "~/dash"


# screen resolution
# cvt 1024 600 60
# xrandr --newmode <line from above>
# xrandr --addmode HDMI-n <mode from above>
# xrandr -s 1680x1050