---
- name: RaspberryPi Configuration
  hosts: raspilocal
  tasks:
    - name: provide ssh key login
      authorized_key: 
        user: "pi" 
        key: "{{ lookup('file', '~/.ssh/renix.pub') }}"
        state: present
    - name: upload deploy key
      copy:
        src: "~/.ssh/renix.pem"
        dest: "/home/pi/.ssh/id_rsa"
        mode: 400
    - name: change sshd configuration
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "{{ item.regex }}"
        line: "{{ item.replace }}"
      loop:
        - { regex: '^(# *)?ChallengeResponseAuthentication', replace: 'ChallengeResponseAuthentication no'}
        - { regex: '^(# *)?PasswordAuthentication', replace: 'PasswordAuthentication no' }
        - { regex: '^(# *)?UsePAM', replace: 'UsePAM no' }
        - { regex: '^(# *)?PermitRootLogin', replace: 'PermitRootLogin no' }
        - { regex: '^(# *)?PermitRootLogin', replace: 'PermitRootLogin prohibit-password' }
      become: yes
    - name: change hostname
      command: "raspi-config nonint do_hostname {{ hostname }}"
      become: yes
    - name: remove piwiz
      apt:
        state: absent
        name: "piwiz"
      become: yes
    - name: add packages
      apt:
        name: "{{item}}"
        state: present
      loop:
        - git
        - python3-venv
      become: yes
    - name: git
      git:
        repo: 'https://github.com/RenixPi/RenixPi.git'
        dest: '~/RenixPi'
        update: no
    - name: reboot
      command: "reboot"
      become: yes
