---
- name: RenixPi Configuration
  hosts: localhost
  roles:
    - common
  tasks:
    - name: rotate screen
      lineinfile:
        path: "/etc/xdg/lxsession/LXDE-pi/autostart"
        line: "@xrandr --output HDMI-1 --rotate right"
    - name: rotate input
      #  -> libinput touchscreen catchall
      # 90° = Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
      # 180° = Option "TransformationMatrix" "-1 0 1 0 -1 1 0 0 1"
      # 270° = Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
      lineinfile:
        path: "/usr/share/X11/xorg.conf.d/40-libinput.conf"
        line: '     Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"'
    - name: disable overscan
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "^(# *)disable_overscan"
        line: "disable_overscan=1"

    - name: "Add grafana apt key"
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: yes
    - name: "Add grafana repo"
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
      become: yes
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mosquitto
        - mosquitto-clients
        - software-properties-common
        - matchbox-window-manager
        - xautomation
        - unclutter
        - grafana
      become: yes
    - name: git
      git:
        repo: 'https://github.com/RenixPi/{{ item }}.git'
        dest: '~/{{ item }}'
        update: no
      loop:
        - "RenixDisplay"
        - "RenixMonitor"
    - name: install RenixDisplay dependencies
      npm:
        path: /home/pi/RenixDisplay
    - name: install RenixMonitor dependencies
      pip:
        requirements: /home/pi/RenixMonitor/requirements.txt
        virtualenv: /home/pi/RenixMonitor/.venv
        virtualenv_command: python3 -m venv
    - name: rtl 433 dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libtool
        - libusb-1.0-0-dev
        - librtlsdr-dev
        - rtl-sdr
        - build-essential
        - autoconf
        - cmake
        - pkg-config
      become: yes
    - name: rtl 433 git clone
      git:
        repo: 'https://github.com/merbanan/rtl_433.git'
        update: no
    - name: create build dir
      file:
        path: "~/rtl_433/build"
        state: directory
    - name: run rtl433 cmake
      ansible.builtin.shell:
        cmd: "{{ item }}"
        chdir: "~/rtl_433/build"
      loop:
        - "cmake .."
        - "make"
        - "make install"
    - name:
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { 'src': 'grafana.ini.j2', 'dest': '/etc/grafana.ini' }

# /usr/share/X11/xorg.conf.d/40-libinput.conf -> libinput touchscreen catchall
# 90° = Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
# 180° = Option "TransformationMatrix" "-1 0 1 0 -1 1 0 0 1"
# 270° = Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"

# /etc/xdg/lxsession/LXDE-pi/autostart ->
# @xrandr --output HDMI-1 --rotate right

# screen resolution
# cvt 1024 600 60
# xrandr --newmode <line from above>
# xrandr --addmode HDMI-n <mode from above>
# xrandr -s 1680x1050