---
- name: RenixPi Configuration
  hosts: localhost
  roles:
    - common
  tasks:
    - name: rotate screen
      lineinfile:
        path: "/etc/xdg/lxsession/LXDE-pi/autostart"
        line: "@xrandr --output HDMI-1 --rotate right"
      become: yes
    - name: rotate input
      #  -> libinput touchscreen catchall
      # 90° = Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
      # 180° = Option "TransformationMatrix" "-1 0 1 0 -1 1 0 0 1"
      # 270° = Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
      lineinfile:
        path: "/usr/share/X11/xorg.conf.d/40-libinput.conf"
        insertafter: ".*?libinput touchscreen catchall"
        line: '        Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"'
      become: yes
    - name: disable overscan
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "^(# *)disable_overscan"
        line: "disable_overscan=1"
      become: yes
    - name: download prometheus and unarchive
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-armv7.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: create prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: pi
        group: pi
      loop:
        - "/etc/prometheus"
        - "/var/lib/prometheus"
      become: yes
    - name: place the binaries
      copy:
        src: "/tmp/prometheus-2.26.0.linux-armv7/{{ item }}"
        dest: "/usr/local/bin"
        owner: pi
        group: pi
        mode: '0500'
      loop:
        - "prometheus"
        - "promtool"
      become: yes
    - name: place the console files
      copy:
        src: "/tmp/prometheus-2.26.0.linux-armv7/{{ item }}"
        dest: "/etc/prometheus"
        owner: pi
        group: pi
      loop:
        - "consoles"
        - "console_libraries"
    - name: prometheus config
      template:
        src: "prometheus.yml.j2"
        dest: "/etc/prometheus/prometheus.yml"
        owner: pi
        group: pi
    - name: prometheus service
      template:
        src: "prometheus.service.j2"
        dest: "/etc/systemd/system/prometheus.service"
      become: yes
    - name: start prometheus
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: prometheus
      become: yes
    - name: install mosquitto
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mosquitto
        - mosquitto-clients
      become: yes
    - name: git
      git:
        repo: 'https://github.com/RenixPi/{{ item }}.git'
        dest: '~/{{ item }}'
        update: no
      loop:
        - "RenixDisplay"
        - "RenixMonitor"
    - name: install RenixDisplay dependencies
      npm:
        path: /home/pi/RenixDisplay
    - name: install RenixMonitor dependencies
      pip:
        requirements: /home/pi/RenixMonitor/requirements.txt
        virtualenv: /home/pi/RenixMonitor/.venv
        virtualenv_command: python3 -m venv
    - name: rtl 433 dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libtool
        - libusb-1.0-0-dev
        - librtlsdr-dev
        - rtl-sdr
        - build-essential
        - autoconf
        - cmake
        - pkg-config
      become: yes
    - name: rtl 433 git clone
      git:
        repo: 'https://github.com/merbanan/rtl_433.git'
        dest: '~/rtl_433'
        update: no
    - name: create build dir
      file:
        path: "~/rtl_433/build"
        state: directory
    - name: run rtl433 cmake
      ansible.builtin.shell:
        cmd: "{{ item }}"
        chdir: "~/rtl_433/build"
      loop:
        - "cmake .."
        - "make"
    - name: rtl433 install
      shell:
        cmd: "make install"
        chdir: "~/rtl_433/build"
      become: yes
    - name:
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { 'src': 'renixmonitor.service.j2', 'dest': '/etc/systemd/system/renixmonitor.service' }
        - { 'src': 'tpmsmonitor.service.j2', 'dest': '/etc/systemd/system/tpmsmonitor.service' }
#    - name: start monitoring services
#      systemd:
#        state: start
#        enabled: yes
#        daemon_reload: yes
#        name: "{{ item }}"
#      loop:
#        - "renixmonitor"
#        - "tpmsmonitor"

# /usr/share/X11/xorg.conf.d/40-libinput.conf -> libinput touchscreen catchall
# 90° = Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
# 180° = Option "TransformationMatrix" "-1 0 1 0 -1 1 0 0 1"
# 270° = Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"

# /etc/xdg/lxsession/LXDE-pi/autostart ->
# @xrandr --output HDMI-1 --rotate right

# screen resolution
# cvt 1024 600 60
# xrandr --newmode <line from above>
# xrandr --addmode HDMI-n <mode from above>
# xrandr -s 1680x1050
