---
- name: RenixPi Configuration
  hosts: localhost
  roles:
    - common
  tasks:
    - name: "Add grafana repo"
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
      become: yes
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mosquitto
        - mosquitto-clients
        - software-properties-common
        - matchbox-window-manager
        - xautomation
        - unclutter
        - grafana
      become: yes
    - name: ensure github.com is a known host
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"
    - name: git
      git:
        repo: 'https://github.com/RenixPi/{{ item }}.git'
        dest: '~/{{ item }}'
        update: no
      loop:
        - "RenixDisplay"
        - "RenixMonitor"
    - name: install RenixDisplay dependencies
      npm:
        path: /home/pi/RenixDisplay
    - name: install RenixMonitor dependencies
      pip:
        requirements: /home/pi/RenixMonitor/requirements.txt
        virtualenv: /home/pi/RenixMonitor/.venv
        virtualenv_command: python3 -m venv
    - name: rtl 433 dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libtool
        - libusb-1.0-0-dev
        - librtlsdr-dev
        - rtl-sdr
        - build-essential
        - autoconf
        - cmake
        - pkg-config
    - name: rtl 433 git clone
      git:
        repo: 'https://github.com/merbanan/rtl_433.git'
        update: no
    - name: create build dir
      file:
        path: "~/rtl_433/build"
        state: directory
    - name: run rtl433 cmake
      ansible.builtin.shell:
        cmd: "{{ item }}"
        chdir: "~/rtl_433/build"
      loop:
        - "cmake .."
        - "make"
        - "make install"
    - name:
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { 'src': 'grafana.ini.j2', 'dest': '/etc/grafana.ini' }


# screen resolution
# cvt 1024 600 60
# xrandr --newmode <line from above>
# xrandr --addmode HDMI-n <mode from above>
# xrandr -s 1680x1050