- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x bionic main
  become: yes
- name: install common dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - git
  become: yes
- name: ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
- name: disable screensaver
  lineinfile:
    path: "/etc/xdg/lxsession/LXDE-pi/autostart"
    line: "{{ item }}"
  loop:
    - '@xset -dpms'
    - '@xset s off'
  become: yes
- name: boot changes
  lineinfile:
    path: "/boot/config.txt"
    line: "{{ item }}"
  loop:
    - 'dtparam=pwr_led_trigger=none'
    - 'dtparam=pwr_led_activelow=off'
    - 'disable_splash=1'
    - 'boot_delay=0'
    - 'initial_turbo=30'
    - 'start_cd=1'
    - '#dtoverlay=sdtweak,overclock_50=10'
  become: yes
- name: set DISPLAY
  lineinfile:
    path: "/home/pi/.bashrc"
    line: "export DISPLAY=:0"


# screen config -> /usr/share/dispsetup.sh

# gtf 600 480 60
# xrandr --newmode "600x480_60.00"  22.19  600 616 672 744  480 481 484 497  -HSync +Vsyn
# xrandr --addmode HDMI-1 "600x480_60.00"




